Controllers/PaymentGTPayController.cs
using System;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Directory;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Payments;
using Nop.Plugin.Payments.GTPay.Models;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Payments;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments.GTPay.Controllers
{
    public class PaymentGTPayController : BasePaymentController
    {
        #region Fields

        private readonly IGenericAttributeService _genericAttributeService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IOrderService _orderService;
        private readonly IPaymentService _paymentService;
        private readonly IPermissionService _permissionService;
        private readonly ILocalizationService _localizationService;
        private readonly ILogger _logger;
        private readonly INotificationService _notificationService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly IWebHelper _webHelper;
        private readonly IWorkContext _workContext;
        private readonly ShoppingCartSettings _shoppingCartSettings;
        private readonly GTPayPaymentSettings _GTPayPaymentSettings;
        private readonly IEncryptionService _encryptionService;
        private readonly CurrencySettings _currencySettings;
        private readonly ICurrencyService _currencyService;

        #endregion

        #region Ctor

        public PaymentGTPayController(
            IGenericAttributeService genericAttributeService,
            IOrderProcessingService orderProcessingService,
            IOrderService orderService,
            IPaymentService paymentService,
            IPermissionService permissionService,
            ILocalizationService localizationService,
            ILogger logger,
            INotificationService notificationService,
            ISettingService settingService,
            IStoreContext storeContext,
            IWebHelper webHelper,
            IWorkContext workContext,
            ShoppingCartSettings shoppingCartSettings,
            GTPayPaymentSettings GTPayPaymentSettings,
            CurrencySettings currencySettings,
            ICurrencyService currencyService,
        IEncryptionService encryptionService)
        {
            this._genericAttributeService = genericAttributeService;
            this._orderService = orderService;
            this._orderProcessingService = orderProcessingService;
            this._paymentService = paymentService;
            this._permissionService = permissionService;
            this._localizationService = localizationService;
            this._logger = logger;
            this._notificationService = notificationService;
            this._settingService = settingService;
            this._shoppingCartSettings = shoppingCartSettings;
            this._storeContext = storeContext;
            this._webHelper = webHelper;
            this._workContext = workContext;
            this._GTPayPaymentSettings = GTPayPaymentSettings;
            this._currencySettings = currencySettings;
            this._currencyService = currencyService;
            this._encryptionService = encryptionService;
        }

        #endregion

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var GTPayPaymentSettings = _settingService.LoadSetting<GTPayPaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                UseSandbox = GTPayPaymentSettings.UseSandbox,
                Title = GTPayPaymentSettings.Title,
                Description = GTPayPaymentSettings.Description,
                WebPayMerchantID = GTPayPaymentSettings.WebPayMerchantID,
                GTPayMerchantID = GTPayPaymentSettings.GTPayMerchantID,
                HashKey = GTPayPaymentSettings.HashKey,
                ActiveStoreScopeConfiguration = storeScope
            };
            if (storeScope > 0)
            {
                model.UseSandbox_OverrideForStore = _settingService.SettingExists(GTPayPaymentSettings, x => x.UseSandbox, storeScope);
                model.Title_OverrideForStore = _settingService.SettingExists(GTPayPaymentSettings, x => x.Title, storeScope);
                model.Description_OverrideForStore = _settingService.SettingExists(GTPayPaymentSettings, x => x.Description, storeScope);
                model.WebPayMerchantID_OverrideForStore = _settingService.SettingExists(GTPayPaymentSettings, x => x.WebPayMerchantID, storeScope);
                model.GTPayMerchantID_OverrideForStore = _settingService.SettingExists(GTPayPaymentSettings, x => x.GTPayMerchantID, storeScope);
                model.HashKey_OverrideForStore = _settingService.SettingExists(GTPayPaymentSettings, x => x.HashKey, storeScope);
            }

            return View("~/Plugins/Payments.GTPay/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [AdminAntiForgery]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var GTPayPaymentSettings = _settingService.LoadSetting<GTPayPaymentSettings>(storeScope);

            //save settings
            GTPayPaymentSettings.UseSandbox = model.UseSandbox;
            GTPayPaymentSettings.Title = model.Title;
            GTPayPaymentSettings.Description = model.Description;
            GTPayPaymentSettings.WebPayMerchantID = model.WebPayMerchantID;
            GTPayPaymentSettings.GTPayMerchantID = model.GTPayMerchantID;
            GTPayPaymentSettings.HashKey = model.HashKey;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            _settingService.SaveSettingOverridablePerStore(GTPayPaymentSettings, x => x.UseSandbox, model.UseSandbox_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(GTPayPaymentSettings, x => x.Title, model.Title_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(GTPayPaymentSettings, x => x.Description, model.Description_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(GTPayPaymentSettings, x => x.WebPayMerchantID, model.WebPayMerchantID_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(GTPayPaymentSettings, x => x.GTPayMerchantID, model.GTPayMerchantID_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(GTPayPaymentSettings, x => x.HashKey, model.HashKey_OverrideForStore, storeScope, false);

            //now clear settings cache
            _settingService.ClearCache();

            _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        //action displaying notification (warning) to a store owner about inaccurate GTPay rounding
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult RoundingWarning(bool passProductNamesAndTotals)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //prices and total aren't rounded, so display warning
            if (passProductNamesAndTotals && !_shoppingCartSettings.RoundPricesDuringCalculation)
                return Json(new { Result = _localizationService.GetResource("Plugins.Payments.GTPay.RoundingWarning") });

            return Json(new { Result = string.Empty });
        }

        public ActionResult ReturnPaymentInfo(IFormCollection form)
        {
            var processor = _paymentService.LoadPaymentMethodBySystemName("Payments.GTPay") as GTPayPaymentProcessor;
            if (processor == null || !_paymentService.IsPaymentMethodActive(processor) || !processor.PluginDescriptor.Installed)
            {
                throw new NopException("GTPay module cannot be loaded");
            }
            string tranx_id = form["gtpay_tranx_id"];
            string tranx_status_code = form["gtpay_tranx_status_code"];
            string tranx_status_msg = form["gtpay_tranx_status_msg"];
            string gtpay_tranx_amt = form["gtpay_tranx_amt"];
            string gtpay_tranx_curr = form["gtpay_tranx_curr"];
            string gtpay_cust_id = form["gtpay_cust_id"];
            string gtpay_gway_name = form["gtpay_gway_name"];
            string gtpay_echo_data = form["gtpay_echo_data"];


            _logger.Information("transid: " + tranx_id);
            _logger.Information("tranx_status_code: " + tranx_status_code);
            _logger.Information("tranx_status_msg: " + tranx_status_msg);

Views/Configure.cshtml
@model Nop.Plugin.Payments.GTPay.Models.ConfigurationModel
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

@*<script>
	$(document).ready(function () {
        $("#@Html.IdFor(model => model.PassProductNamesAndTotals)").click(togglePassProductNamesAndTotals);
	    togglePassProductNamesAndTotals();
	});

    function togglePassProductNamesAndTotals() {
        warningValidation('@Url.Action("RoundingWarning", "PaymentGTPay")', '@Html.NameFor(model => model.PassProductNamesAndTotals)',
            { passProductNamesAndTotals: $('#@Html.IdFor(model => model.PassProductNamesAndTotals)').is(':checked') });
    }
</script>*@

<form asp-controller="PaymentGTPay" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                @Html.Raw(T("Plugins.Payments.GTPay.Instructions", $"{webHelper.GetStoreLocation()}Plugins/PaymentGTPay/PaymentHandler"))
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSandbox_OverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Title_OverrideForStore" asp-input="Title" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Title" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Title" />
                        <span asp-validation-for="Title"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Description_OverrideForStore" asp-input="Description" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Description" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Description" />
                        <span asp-validation-for="Description"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="WebPayMerchantID_OverrideForStore" asp-input="WebPayMerchantID" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="WebPayMerchantID" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="WebPayMerchantID" />
                        <span asp-validation-for="WebPayMerchantID"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="GTPayMerchantID_OverrideForStore" asp-input="GTPayMerchantID" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="GTPayMerchantID" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="GTPayMerchantID" />
                        <span asp-validation-for="GTPayMerchantID"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="HashKey_OverrideForStore" asp-input="HashKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="HashKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="HashKey" />
                        <span asp-validation-for="HashKey"></span>
                    </div>
                </div>              
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Views/PaymentInfo.cshtml
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "";
}
    <div class="row">
        <div class="col-md-2">
            <img src="@Url.Content($"{webHelper.GetStoreLocation()}Plugins/Payments.GTPay/logo.jpg")" alt="GTPay" />            
        </div>
        <div class="col-md-8">
            <b>@T("Plugins.Payments.GTPay.Fields.RedirectionTip")</b>
        </div>
    </div>

Views/ReturnPaymentInfo.cshtml
@model Nop.Plugin.Payments.GTPay.Models.ReturnPaymentInfoModel
@{
    Layout = "_ColumnsOne";

    //title
    Html.AddTitleParts("Payment Information");
    //page class
    Html.AppendPageCssClassParts("html-checkout-page");
    Html.AppendPageCssClassParts("html-order-completed-page");
}

<div class="page checkout-page order-completed-page">   
    <div class="page-title">
        <h1>GTPay Payment Declined</h1>
    </div>
    <div class="page-body checkout-data">      
        <div class="section order-completed">
            <div class="title">
                <strong>Payment is declined</strong>
            </div>
            <div class="details">
                <div class="order-number">
                    <strong>Order Number: @Html.Raw(Model.OrderId.ToString())</strong>
                </div>
                <div class="order-number">
                    <strong>Description:  @Html.Raw(Model.DescriptionText)</strong>
                </div>
                <div class="order-number">
                    <strong>Status Code: @Html.Raw(Model.StatusCode)</strong>
                </div>
                <div class="order-number">
                    <strong>Message: @Html.Raw(Model.StatusMessage)</strong>
                </div>
                <div class="details-link">
                    <a href="@Url.RouteUrl("OrderDetails", new { orderID = Model.OrderId })">@T("Checkout.PlacedOrderDetails")</a>
                </div>
            </div>
            <div class="buttons">
                <input type="button" value="@T("Checkout.ThankYou.Continue")" class="button-1 order-completed-continue-button" onclick="setLocation('@Url.RouteUrl("HomePage")')" />
            </div>
        </div>
    </div>
</div>